-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 20:29:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema skyroof
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skyroof
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skyroof` DEFAULT CHARACTER SET utf8 ;
USE `skyroof` ;

-- -----------------------------------------------------
-- Table `skyroof`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skyroof`.`projects` (
  `projectID` INT(255) NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`projectID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skyroof`.`issuestatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skyroof`.`issuestatus` (
  `statusID` INT(255) NOT NULL AUTO_INCREMENT,
  `statusDescription` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`statusID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skyroof`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skyroof`.`users` (
  `username` VARCHAR(255) NOT NULL,
  `pswd` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `userID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skyroof`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skyroof`.`issues` (
  `issueID` INT(255) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `issueDescription` VARCHAR(255) NOT NULL,
  `issueType` VARCHAR(255) NOT NULL,
  `otherDetails` VARCHAR(255) NULL DEFAULT NULL,
  `isHidden` TINYINT NOT NULL,
  `projectID` INT(255) NOT NULL,
  `statusID` INT(255) NOT NULL,
  `assignor` INT NOT NULL,
  `assignee` INT NOT NULL,
  PRIMARY KEY (`issueID`, `projectID`, `statusID`),
  INDEX `fk_issues_projects_idx` (`projectID` ASC),
  INDEX `fk_issues_issuestatus1_idx` (`statusID` ASC),
  INDEX `fk_issues_users2_idx` (`assignor` ASC),
  INDEX `fk_issues_users1_idx` (`assignee` ASC),
  CONSTRAINT `fk_issues_projects`
    FOREIGN KEY (`projectID`)
    REFERENCES `skyroof`.`projects` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_issuestatus1`
    FOREIGN KEY (`statusID`)
    REFERENCES `skyroof`.`issuestatus` (`statusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_users2`
    FOREIGN KEY (`assignor`)
    REFERENCES `skyroof`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_users1`
    FOREIGN KEY (`assignee`)
    REFERENCES `skyroof`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skyroof`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skyroof`.`permission` (
  `permissionID` INT NOT NULL,
  `userID` INT NOT NULL,
  `projectID` INT(255) NOT NULL,
  `permissionDescriptionl` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`, `projectID`, `permissionID`),
  INDEX `fk_permission_users1_idx` (`userID` ASC),
  INDEX `fk_permission_projects1_idx` (`projectID` ASC),
  CONSTRAINT `fk_permission_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `skyroof`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_projects1`
    FOREIGN KEY (`projectID`)
    REFERENCES `skyroof`.`projects` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
